from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1100, 600)
        MainWindow.setAutoFillBackground(False)
        self.main_widget = QtGui.QWidget(MainWindow)
        self.main_widget.setObjectName(_fromUtf8("main_widget"))
        self.settings_frame = QtGui.QTabWidget(self.main_widget)
        self.settings_frame.setGeometry(QtCore.QRect(730, 20, 251, 321))
        self.settings_frame.setObjectName(_fromUtf8("settings_frame"))
        self.mask_grid = QtGui.QWidget()
        self.mask_grid.setObjectName(_fromUtf8("mask_grid"))
        self.Mask_settings = QtGui.QGridLayout(self.mask_grid)
        self.Mask_settings.setObjectName(_fromUtf8("Mask_settings"))
        self.low_h_label = QtGui.QLabel(self.mask_grid)
        self.low_h_label.setAlignment(QtCore.Qt.AlignCenter)
        self.low_h_label.setObjectName(_fromUtf8("low_h_label"))
        self.Mask_settings.addWidget(self.low_h_label, 2, 1, 1, 1)
        self.low_h = QtGui.QSlider(self.mask_grid)
        self.low_h.setMaximum(180)
        self.low_h.setOrientation(QtCore.Qt.Horizontal)
        self.low_h.setObjectName(_fromUtf8("low_h"))
        self.Mask_settings.addWidget(self.low_h, 3, 1, 1, 1)
        self.up_s_label = QtGui.QLabel(self.mask_grid)
        self.up_s_label.setAlignment(QtCore.Qt.AlignCenter)
        self.up_s_label.setObjectName(_fromUtf8("up_s_label"))
        self.Mask_settings.addWidget(self.up_s_label, 5, 0, 1, 1)
        self.up_v_label = QtGui.QLabel(self.mask_grid)
        self.up_v_label.setAlignment(QtCore.Qt.AlignCenter)
        self.up_v_label.setObjectName(_fromUtf8("up_v_label"))
        self.Mask_settings.addWidget(self.up_v_label, 7, 0, 1, 1)
        self.low_v = QtGui.QSlider(self.mask_grid)
        self.low_v.setMaximum(255)
        self.low_v.setOrientation(QtCore.Qt.Horizontal)
        self.low_v.setObjectName(_fromUtf8("low_v"))
        self.Mask_settings.addWidget(self.low_v, 8, 1, 1, 1)
        self.up_s = QtGui.QSlider(self.mask_grid)
        self.up_s.setMaximum(255)
        self.up_s.setOrientation(QtCore.Qt.Horizontal)
        self.up_s.setObjectName(_fromUtf8("up_s"))
        self.Mask_settings.addWidget(self.up_s, 6, 0, 1, 1)
        self.low_s_label = QtGui.QLabel(self.mask_grid)
        self.low_s_label.setAlignment(QtCore.Qt.AlignCenter)
        self.low_s_label.setObjectName(_fromUtf8("low_s_label"))
        self.Mask_settings.addWidget(self.low_s_label, 5, 1, 1, 1)
        self.low_tres = QtGui.QLabel(self.mask_grid)
        self.low_tres.setAlignment(QtCore.Qt.AlignCenter)
        self.low_tres.setObjectName(_fromUtf8("low_tres"))
        self.Mask_settings.addWidget(self.low_tres, 1, 1, 1, 1)
        self.up_v = QtGui.QSlider(self.mask_grid)
        self.up_v.setMaximum(255)
        self.up_v.setOrientation(QtCore.Qt.Horizontal)
        self.up_v.setObjectName(_fromUtf8("up_v"))
        self.Mask_settings.addWidget(self.up_v, 8, 0, 1, 1)
        self.up_h = QtGui.QSlider(self.mask_grid)
        self.up_h.setMaximum(180)
        self.up_h.setOrientation(QtCore.Qt.Horizontal)
        self.up_h.setObjectName(_fromUtf8("up_h"))
        self.Mask_settings.addWidget(self.up_h, 3, 0, 1, 1)
        self.up_tres = QtGui.QLabel(self.mask_grid)
        self.up_tres.setAlignment(QtCore.Qt.AlignCenter)
        self.up_tres.setObjectName(_fromUtf8("up_tres"))
        self.Mask_settings.addWidget(self.up_tres, 1, 0, 1, 1)
        self.low_v_label = QtGui.QLabel(self.mask_grid)
        self.low_v_label.setAlignment(QtCore.Qt.AlignCenter)
        self.low_v_label.setObjectName(_fromUtf8("low_v_label"))
        self.Mask_settings.addWidget(self.low_v_label, 7, 1, 1, 1)
        self.low_s = QtGui.QSlider(self.mask_grid)
        self.low_s.setMaximum(255)
        self.low_s.setOrientation(QtCore.Qt.Horizontal)
        self.low_s.setObjectName(_fromUtf8("low_s"))
        self.Mask_settings.addWidget(self.low_s, 6, 1, 1, 1)
        self.show_mask = QtGui.QCheckBox(self.mask_grid)
        self.show_mask.setObjectName(_fromUtf8("show_mask"))
        self.Mask_settings.addWidget(self.show_mask, 9, 0, 1, 1)
        self.up_h_label = QtGui.QLabel(self.mask_grid)
        self.up_h_label.setAlignment(QtCore.Qt.AlignCenter)
        self.up_h_label.setObjectName(_fromUtf8("up_h_label"))
        self.Mask_settings.addWidget(self.up_h_label, 2, 0, 1, 1)
        self.settings_frame.addTab(self.mask_grid, _fromUtf8(""))
        self.direct_control_grid = QtGui.QWidget()
        self.direct_control_grid.setObjectName(_fromUtf8("direct_control_grid"))
        self.gridLayout = QtGui.QGridLayout(self.direct_control_grid)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.control_layout = QtGui.QGroupBox(self.direct_control_grid)
        self.control_layout.setObjectName(_fromUtf8("control_layout"))
        self.Direc_control = QtGui.QGridLayout(self.control_layout)
        self.Direc_control.setObjectName(_fromUtf8("Direc_control"))
        self.y_speed_label = QtGui.QLabel(self.control_layout)
        self.y_speed_label.setAlignment(QtCore.Qt.AlignCenter)
        self.y_speed_label.setObjectName(_fromUtf8("y_speed_label"))
        self.Direc_control.addWidget(self.y_speed_label, 2, 1, 1, 1)
        self.stop_btn = QtGui.QPushButton(self.control_layout)
        self.stop_btn.setObjectName(_fromUtf8("stop_btn"))
        self.Direc_control.addWidget(self.stop_btn, 5, 1, 1, 1)
        self.land_btn = QtGui.QPushButton(self.control_layout)
        self.land_btn.setObjectName(_fromUtf8("land_btn"))
        self.Direc_control.addWidget(self.land_btn, 5, 0, 1, 1)
        self.x_speed_label = QtGui.QLabel(self.control_layout)
        self.x_speed_label.setAlignment(QtCore.Qt.AlignCenter)
        self.x_speed_label.setObjectName(_fromUtf8("x_speed_label"))
        self.Direc_control.addWidget(self.x_speed_label, 2, 0, 1, 1)
        self.y_speed_sl = QtGui.QSlider(self.control_layout)
        self.y_speed_sl.setStatusTip(_fromUtf8(""))
        self.y_speed_sl.setMinimum(-2)
        self.y_speed_sl.setMaximum(2)
        self.y_speed_sl.setOrientation(QtCore.Qt.Horizontal)
        self.y_speed_sl.setObjectName(_fromUtf8("y_speed_sl"))
        self.Direc_control.addWidget(self.y_speed_sl, 3, 1, 1, 1)
        self.takeoff_btn = QtGui.QPushButton(self.control_layout)
        self.takeoff_btn.setAutoFillBackground(False)
        self.takeoff_btn.setIconSize(QtCore.QSize(16, 16))
        self.takeoff_btn.setObjectName(_fromUtf8("takeoff_btn"))
        self.Direc_control.addWidget(self.takeoff_btn, 4, 0, 1, 1)
        self.x_horizontal = QtGui.QGroupBox(self.control_layout)
        self.x_horizontal.setObjectName(_fromUtf8("x_horizontal"))
        self.x_speed_pos = QtGui.QHBoxLayout(self.x_horizontal)
        self.x_speed_pos.setObjectName(_fromUtf8("x_speed_pos"))
        self.x_speed_sl = QtGui.QSlider(self.x_horizontal)
        self.x_speed_sl.setStatusTip(_fromUtf8(""))
        self.x_speed_sl.setMinimum(-2)
        self.x_speed_sl.setMaximum(2)
        self.x_speed_sl.setOrientation(QtCore.Qt.Vertical)
        self.x_speed_sl.setObjectName(_fromUtf8("x_speed_sl"))
        self.x_speed_pos.addWidget(self.x_speed_sl)
        self.Direc_control.addWidget(self.x_horizontal, 3, 0, 1, 1)
        self.enable_d_control = QtGui.QCheckBox(self.control_layout)
        self.enable_d_control.setObjectName(_fromUtf8("enable_d_control"))
        self.Direc_control.addWidget(self.enable_d_control, 0, 0, 1, 1)
        self.reset_btn = QtGui.QPushButton(self.control_layout)
        self.reset_btn.setObjectName(_fromUtf8("reset_btn"))
        self.Direc_control.addWidget(self.reset_btn, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.control_layout, 0, 0, 1, 1)
        self.settings_frame.addTab(self.direct_control_grid, _fromUtf8(""))
        self.camera_img = QtGui.QLabel(self.main_widget)
        self.camera_img.setGeometry(QtCore.QRect(50, 20, 461, 321))
        self.camera_img.setText(_fromUtf8(""))
        self.camera_img.setObjectName(_fromUtf8("label"))
        MainWindow.setCentralWidget(self.main_widget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.settings_frame.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.low_h_label.setText(_translate("MainWindow", "Hue", None))
        self.up_s_label.setText(_translate("MainWindow", "Saturation", None))
        self.up_v_label.setText(_translate("MainWindow", "Value", None))
        self.low_s_label.setText(_translate("MainWindow", "Saturation", None))
        self.low_tres.setText(_translate("MainWindow", "Lower threshold", None))
        self.up_tres.setText(_translate("MainWindow", "Upper threshold", None))
        self.low_v_label.setText(_translate("MainWindow", "Value", None))
        self.show_mask.setText(_translate("MainWindow", "Show mask", None))
        self.up_h_label.setText(_translate("MainWindow", "Hue", None))
        self.y_speed_label.setText(_translate("MainWindow", "Y speed", None))
        self.stop_btn.setText(_translate("MainWindow", "Stop", None))
        self.land_btn.setText(_translate("MainWindow", "Land", None))
        self.x_speed_label.setText(_translate("MainWindow", "X speed", None))
        self.takeoff_btn.setText(_translate("MainWindow", "Take off", None))
        self.enable_d_control.setText(_translate("MainWindow", "Enable", None))
        self.reset_btn.setText(_translate("MainWindow", "Reset", None))
        self.settings_frame.setTabText(self.settings_frame.indexOf(self.direct_control_grid), \
        _translate("MainWindow", "Direct control", None))
        self.settings_frame.setTabText(self.settings_frame.indexOf(self.mask_grid), _translate("MainWindow", "Mask", None))

